# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: DFTB+ Developer pages
email: info@dftbplus.org
description: > # this means to ignore newlines until "baseurl:"
  Development information of DFTB+ related projects
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://devel.dftbplus.org" # the base hostname & protocol for your site
github_username:  github.com/dftbplus

# Build settings
markdown: kramdown
